#!/usr/bin/env python3
"""
Fill the crosswalk's OPEN cross-reference cells from sources that are not VMH.

  MNXref + ModelSEED  ->  MASTER_CROSSWALK.xrefs.tsv   (one row per filled cell)

MASTER_CROSSWALK.tsv is NOT touched. It is generated by
`tools/normalize_crosswalk.py` from the VMH extract and gated by
`make crosswalk-check`, which compares it byte for byte against
normalize(extract). Writing enrichment into it would break that gate and erase
the distinction the gate exists to protect: what VMH said, versus what we added.
So this ships a SIDECAR, and every row in it names the source of that one cell.

Why it is worth having
----------------------
1. `inchiKey` is OPEN in all 2,797 rows. THIRD-PARTY-DATA.json says so out loud:
   "Any plan treating InChIKey as an available join key is building on nothing."
   ModelSEED supplies a structure hash for a large minority of the table.
2. `seed` is 4.3% populated. MNXref raises it by an order of magnitude.
3. MNXref is CC BY 4.0 and independent of VMH. Every cell it CORROBORATES is a
   cell the table no longer needs VMH's mapping to justify — remedy 3 in
   MASTER_CROSSWALK.NOTICE.md ("rebuild the cross-references from each registry
   directly"), measured rather than asserted.
4. Where MNXref DISAGREES with a populated VMH cell, that is a finding. It is
   written to a conflicts table and never silently applied.

Fail-closed rules
-----------------
* Only cells that read OPEN are ever filled. A populated cell is never rewritten.
* MNXref marks superseded accessions `secondary/obsolete/fantasy identifier` and
  prefixes them `M_`. Both are dropped. Filling a cell with a deprecated id is
  worse than leaving it OPEN, which is the whole thesis of this repository.
* Values are emitted in the canonical CURIE form normalize_crosswalk.py uses, so
  the sidecar and the table speak the same dialect.
* KEGG- and HMDB-derived cells carry licences that forbid what this repository's
  Apache-2.0 permits, so they are withheld unless --include-restricted is given.

  python3 tools/enrich_crosswalk_xrefs.py --fetch     refresh .xref_cache/
  python3 tools/enrich_crosswalk_xrefs.py             regenerate the sidecar
  python3 tools/enrich_crosswalk_xrefs.py --check     verify, exit 1 on drift
  python3 tools/enrich_crosswalk_xrefs.py --report    counts only, write nothing
"""

from __future__ import annotations

import argparse
import csv
import io
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANONICAL = ROOT / "MASTER_CROSSWALK.tsv"
SIDECAR = ROOT / "MASTER_CROSSWALK.xrefs.tsv"
CONFLICTS = ROOT / "MASTER_CROSSWALK.xrefs.conflicts.tsv"
CACHE = ROOT / ".xref_cache"

MNX_XREF_URL = "https://www.metanetx.org/ftp/latest/chem_xref.tsv"
SEED_URL = ("https://raw.githubusercontent.com/ModelSEED/ModelSEEDDatabase/"
            "master/Biochemistry/compounds.tsv")

OPEN = "OPEN"
DEPRECATED = "secondary/obsolete/fantasy identifier"

SIDECAR_COLUMNS = ["vmh", "column", "value", "mnx", "source", "source_version",
                   "licence", "licence_class"]
CONFLICT_COLUMNS = ["vmh", "column", "canonical_value", "external_value", "mnx", "source"]

# MNXref namespace -> the crosswalk column it can fill.
NAMESPACE_COLUMN = {
    "chebi": "chebi",
    "seedM": "seed",
    "kegg.compound": "kegg",
    "hmdb": "hmdb",
}

# Licence per emitted column. Quoted from each source's own statement, which is
# carried verbatim in the chem_xref.tsv header block — the artefact, not a
# registry's summary of it.
LICENCE = {
    "chebi": ("ChEBI", "244",
              "All data non-proprietary or derived from a non-proprietary source; "
              "freely accessible and available to anyone", "open"),
    "seed": ("ModelSEED", "2.6.1",
             "CC BY 4.0 (ModelSEED GitHub repository)", "open"),
    "inchiKey": ("ModelSEED", "2.6.1",
                 "CC BY 4.0 (ModelSEED GitHub repository)", "open"),
    "kegg": ("KEGG", "111.0+/07-27",
             "Non-academic use requires a commercial license (kegg.jp/kegg/legal.html, "
             "last updated 2024-10-01)", "restricted"),
    "hmdb": ("HMDB", "5.0",
             "Use and re-distribution, in whole or in part, for commercial purposes "
             "requires explicit permission of the authors (hmdb.ca/about)", "restricted"),
}

MNX_VERSION = "4.5"


# --- canonical CURIE forms, matching tools/normalize_crosswalk.py ------------

def _curie(column: str, accession: str) -> str | None:
    """Canonical form, or None if the accession is not well-formed for its column."""
    if column == "chebi":
        return f"chebi:{accession}" if re.fullmatch(r"\d+", accession) else None
    if column == "kegg":
        return f"kegg:{accession}" if re.fullmatch(r"C\d{5}", accession) else None
    if column == "hmdb":
        m = re.fullmatch(r"HMDB(\d+)", accession)
        return f"hmdb:HMDB{int(m.group(1)):07d}" if m else None
    if column == "seed":
        return accession if re.fullmatch(r"cpd\d{5}", accession) else None
    if column == "inchiKey":
        return accession if re.fullmatch(r"[A-Z]{14}-[A-Z]{10}-[A-Z]", accession) else None
    return None


# --- cache ------------------------------------------------------------------

def _fetch(argv_subset: Path | None) -> None:
    """Reduce the two upstream tables to the rows this repository actually uses.

    chem_xref.tsv is ~680 MB. Nothing is committed and nothing that large is kept:
    the pass below writes only rows whose MNXref anchor is reachable from one of
    our 2,797 VMH ids, which is a few hundred kilobytes.
    """
    CACHE.mkdir(exist_ok=True)
    wanted_vmh = {r["vmh"] for r in _read_canonical()}

    stream: io.TextIOBase
    if argv_subset is not None:
        stream = argv_subset.open(encoding="utf-8")
    else:
        req = urllib.request.Request(MNX_XREF_URL, headers={"User-Agent": "biology-as-code"})
        stream = io.TextIOWrapper(urllib.request.urlopen(req), encoding="utf-8", errors="replace")

    keep_ns = {"vmhM", *NAMESPACE_COLUMN}
    rows: list[tuple[str, str, str]] = []
    with stream:
        for line in stream:
            if line.startswith("#"):
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 3 or parts[2] == DEPRECATED:
                continue
            source, mnx = parts[0], parts[1]
            ns, _, acc = source.partition(":")
            if ns not in keep_ns or acc.startswith("M_"):
                continue
            rows.append((ns, acc, mnx))

    anchors = {mnx for ns, acc, mnx in rows if ns == "vmhM" and acc in wanted_vmh}
    kept = [r for r in rows if r[2] in anchors]
    with (CACHE / "mnx_xref.tsv").open("w", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh, delimiter="\t", lineterminator="\n")
        w.writerow(["namespace", "accession", "mnx"])
        w.writerows(sorted(kept))
    print(f"cached  {len(kept):>7} MNXref rows over {len(anchors)} anchors -> {CACHE.name}/mnx_xref.tsv")

    seed_ids = {acc for ns, acc, _ in kept if ns == "seedM"}
    req = urllib.request.Request(SEED_URL, headers={"User-Agent": "biology-as-code"})
    with urllib.request.urlopen(req) as resp:
        text = resp.read().decode("utf-8", errors="replace")
    keys = [(r["id"], r["inchikey"])
            for r in csv.DictReader(io.StringIO(text), delimiter="\t")
            if r["id"] in seed_ids and r.get("inchikey") not in (None, "", "null")]
    with (CACHE / "seed_inchikey.tsv").open("w", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh, delimiter="\t", lineterminator="\n")
        w.writerow(["seed", "inchikey"])
        w.writerows(sorted(keys))
    print(f"cached  {len(keys):>7} ModelSEED InChIKeys -> {CACHE.name}/seed_inchikey.tsv")


def _read_canonical() -> list[dict[str, str]]:
    with CANONICAL.open(encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh, delimiter="\t"))


def _read_cache() -> tuple[dict[str, str], dict[str, dict[str, list[str]]], dict[str, str]]:
    xref = CACHE / "mnx_xref.tsv"
    if not xref.is_file():
        sys.exit(f"no cache at {xref} — run with --fetch first")
    vmh2mnx: dict[str, str] = {}
    by_mnx: dict[str, dict[str, list[str]]] = {}
    with xref.open(encoding="utf-8", newline="") as fh:
        for r in csv.DictReader(fh, delimiter="\t"):
            ns, acc, mnx = r["namespace"], r["accession"], r["mnx"]
            if ns == "vmhM":
                vmh2mnx.setdefault(acc, mnx)
            elif ns in NAMESPACE_COLUMN:
                by_mnx.setdefault(mnx, {}).setdefault(NAMESPACE_COLUMN[ns], []).append(acc)
    seed_ik: dict[str, str] = {}
    ikf = CACHE / "seed_inchikey.tsv"
    if ikf.is_file():
        with ikf.open(encoding="utf-8", newline="") as fh:
            seed_ik = {r["seed"]: r["inchikey"] for r in csv.DictReader(fh, delimiter="\t")}
    return vmh2mnx, by_mnx, seed_ik


# --- the merge --------------------------------------------------------------

def build(include_restricted: bool) -> tuple[list[list[str]], list[list[str]], dict]:
    canonical = _read_canonical()
    vmh2mnx, by_mnx, seed_ik = _read_cache()

    fills: list[list[str]] = []
    conflicts: list[list[str]] = []
    stats = {"rows": len(canonical), "anchored": 0, "fill": {}, "corroborated": {},
             "conflict": {}, "withheld": 0}

    for row in canonical:
        mnx = vmh2mnx.get(row["vmh"])
        if not mnx:
            continue
        stats["anchored"] += 1
        offered = dict(by_mnx.get(mnx, {}))

        # InChIKey is not an MNXref namespace; it comes from the SEED ids MNXref
        # anchored, which is the only reason this column can be filled at all.
        for seed_acc in offered.get("seed", []):
            if seed_acc in seed_ik:
                offered.setdefault("inchiKey", []).append(seed_ik[seed_acc])
                break

        for column, accessions in offered.items():
            values = [v for v in (_curie(column, a) for a in accessions) if v]
            if not values:
                continue
            source, version, licence, klass = LICENCE[column]
            current = row[column]
            if current != OPEN:
                if current in values:
                    stats["corroborated"][column] = stats["corroborated"].get(column, 0) + 1
                else:
                    stats["conflict"][column] = stats["conflict"].get(column, 0) + 1
                    conflicts.append([row["vmh"], column, current, ";".join(sorted(values)),
                                      mnx, source])
                continue
            if klass == "restricted" and not include_restricted:
                stats["withheld"] += 1
                continue
            stats["fill"][column] = stats["fill"].get(column, 0) + 1
            fills.append([row["vmh"], column, ";".join(sorted(values)), mnx,
                          source, version, licence, klass])

    fills.sort(key=lambda r: (r[0], r[1]))
    conflicts.sort(key=lambda r: (r[0], r[1]))
    return fills, conflicts, stats


def _render(rows: list[list[str]], header: list[str]) -> str:
    buf = io.StringIO()
    w = csv.writer(buf, delimiter="\t", lineterminator="\n")
    w.writerow(header)
    w.writerows(rows)
    return buf.getvalue()


def _report(stats: dict, include_restricted: bool) -> None:
    canonical = _read_canonical()
    total = len(canonical)
    print(f"crosswalk rows {total}   anchored in MNXref {stats['anchored']}")
    print(f"\n{'column':10} {'today':>13} {'+ sidecar':>13} {'corroborated':>13} {'conflicts':>10}")
    for column in ("inchiKey", "seed", "chebi", "hmdb", "kegg"):
        have = sum(1 for r in canonical if r[column] != OPEN)
        add = stats["fill"].get(column, 0)
        klass = LICENCE[column][3]
        mark = "  (withheld)" if klass == "restricted" and not include_restricted else ""
        print(f"{column:10} {have:>6} {100*have/total:>5.1f}% "
              f"{have+add:>6} {100*(have+add)/total:>5.1f}% "
              f"{stats['corroborated'].get(column, 0):>13} "
              f"{stats['conflict'].get(column, 0):>10}{mark}")
    if stats["withheld"]:
        print(f"\n{stats['withheld']} cell(s) withheld: KEGG/HMDB terms do not permit what "
              f"Apache-2.0 grants. --include-restricted to emit them.")


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--fetch", action="store_true", help="refresh .xref_cache/ from upstream")
    ap.add_argument("--from-subset", type=Path, default=None,
                    help="with --fetch, read a pre-filtered chem_xref instead of downloading")
    ap.add_argument("--check", action="store_true", help="verify on-disk output, exit 1 on drift")
    ap.add_argument("--report", action="store_true", help="print counts, write nothing")
    ap.add_argument("--include-restricted", action="store_true",
                    help="also emit KEGG- and HMDB-derived cells")
    args = ap.parse_args(argv)

    if args.fetch:
        _fetch(args.from_subset)
        if not (args.check or args.report):
            return 0

    fills, conflicts, stats = build(args.include_restricted)
    sidecar = _render(fills, SIDECAR_COLUMNS)
    conflict_text = _render(conflicts, CONFLICT_COLUMNS)

    if args.report:
        _report(stats, args.include_restricted)
        return 0

    if args.check:
        drift = []
        for path, want in ((SIDECAR, sidecar), (CONFLICTS, conflict_text)):
            got = path.read_text(encoding="utf-8") if path.is_file() else ""
            if got != want:
                drift.append(path.name)
        if drift:
            print("DRIFT " + ", ".join(drift) + " — rerun without --check")
            return 1
        print(f"OK    {len(fills)} sidecar rows, {len(conflicts)} conflicts, in sync")
        return 0

    SIDECAR.write_text(sidecar, encoding="utf-8")
    CONFLICTS.write_text(conflict_text, encoding="utf-8")
    _report(stats, args.include_restricted)
    print(f"\nwrote {SIDECAR.name} ({len(fills)} rows) and "
          f"{CONFLICTS.name} ({len(conflicts)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
